browser: # Basic Configuration for Browser
    headers:
        accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
        user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36
        accept-encoding: accept-encoding
        accept-language: ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7
    scraping_interval: 1 

naver_search: # 
    address: https://search.shopping.naver.com/search/all.nhn
    headers:
        referer: http://pc.shopping2.naver.com/
    params:
        query: 
        pagingIndex: 1
        pagingSize: 40
        viewType: list
        sort: review
        frm: NVSHATC
    redirect_internal:
        - search.shopping.naver.com
        - storefarm.naver.com
        - swindow.naver.com
    redirect_external:
        - cr2.shopping.naver.com

naver_category:
    address: https://search.shopping.naver.com/search/category.nhn
    params:
        brand:
        cat_id:
        frm: NVSHBRD
        pagingIndex: 1
        pagingSize : 40
        sort: rel
        viewType: list

naver_shopping:
    address: https://search.shopping.naver.com/detail/review_list.nhn
    headers:
        referer: http://pc.shopping2.naver.com/
    params:
        nvMid:
        page: 
        reviewSort: registration
        reviewSeq: 
        reviewType: all
